### ISSUE TITLE
Makes Home Assistant Run Very Slow

### ISSUE THREAD

**Issue by gabrielwalton** [ianByrne/HASS-ukho_tides#10]
I set up this integration as per the instructions with an Apex graph showing tidal curve and the text box displaying tide stats. After a few minutes of this running home assistant starts to become very slow.

**Comment by ianByrne** [comment]
hi @gabrielwalton - sorry to hear you're running into some odd issues with performance. Are you still experiencing the issue? Can you paste your ApexCharts card config here?

**Comment by ianByrne** [comment]
I will now close this - please feel free to re-open if the issue persists
