### ISSUE TITLE
No data issue

### ISSUE THREAD

**Issue by meanioni99** [ianByrne/HASS-ukho_tides#11]
Hi, great plugin which worked for a while but has stopped showing data. When I checked the logs, I saw that it was because I was getting errors saying the quota for free requests under the discovery tier of the UKHO API had been exceeded? Any thoughts?

**Comment by ianByrne** [comment]
Hi @meanioni99 - sorry to hear you're seeing some odd errors. According to [UKHO's docs](https://admiraltyapi.portal.azure-api.net/products/uk-tidal-api), you should be entitled to 10 calls per second and 10,000 calls per month. If you're somehow exceeding this limit, it sounds like a glitch with the integration - it should only be making an API call once every 60 mins. Can you try uninstalling and re-installing the integration?

**Comment by ianByrne** [comment]
I will now close this - please feel free to re-open if the issue persists
