### ISSUE TITLE
[Feature Request] Parameters might be improved

### ISSUE THREAD

**Issue by ISO8807** [ianByrne/HASS-ukho_tides#12]
This integration works nicely for me, and is the best explained integration I've seen. Some improvements might be made in parameters.

The list of tidal stations isn't in a useful order, so it's hard to find a particular station. It's probably in the order supplied by UKHO. Could the integration sort the names into alphabetical order?

The description for using ApexCharts is slightly out of date. What used to be `extend_to_end: false` should now be `extend_to: end`.

The integration appears to get two days' worth of tides. Could there be a parameter to set the number of days?

**Comment by ISO8807** [comment]
Looking at the UKHO analytics, it seems that the integration might be requesting tide data every 30 minutes (which seems a bit frequent). Could this interval be a parameter as well?

**Comment by ianByrne** [comment]
Hi @ISO8807 - many thanks for your comments, suggestions, and the heads up on the updated Apex Charts docs - I see someone else has submitted #15 to fix the docs, which has now been merged.

I'm afraid I do not have a lot of capacity these days to contribute to this project much anymore, however do please feel free to submit any PRs for added or improved functionality.
