### ISSUE TITLE
No longer works after upgrading to HA 2023.5

### ISSUE THREAD

**Issue by nharrison00** [ianByrne/HASS-ukho_tides#16]
Upgraded to HA 2023.5 last night and it broke the okho_tides integration (and some others!).  On the Settings, Integrations page is shows an error "Failed to set up: Import error".

**Comment by neilmartin83** [comment]
Same here - I'll try to get some debug logs up after work later today.

**Comment by ianByrne** [comment]
Yep I'm seeing the same thing after updating. Will poke about tonight

**Comment by neilmartin83** [comment]
Thanks @ianByrne 

Here's the log entry:

```
2023-05-04 17:54:39.683 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration ukho_tides to set up ukho_tides configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
```

It looks like this is related to the deprecation of `async_get_registry` as used in https://github.com/ianByrne/HASS-ukho_tides/blob/main/custom_components/ukho_tides/config_flow.py#L30 and https://github.com/ianByrne/HASS-ukho_tides/blob/main/custom_components/ukho_tides/config_flow.py#L215

I'm a Python idiot but it might be as simple as just replacing `async_get_registry` with `async_get` in those two lines?

**Comment by nharrison00** [comment]
Good call neilmartin83, I manually edited config_flow.py to change  async_get_registry to async_get in those two places and it now works. Had to restart HA and wait a little bit for the data to populate but otherwise - back to normal. 

Neil


> Thanks @ianByrne
> 
> Here's the log entry:
> 
> ```
> 2023-05-04 17:54:39.683 ERROR (MainThread) [homeassistant.config_entries] Error importing platform config_flow from integration ukho_tides to set up ukho_tides configuration entry: cannot import name 'async_get_registry' from 'homeassistant.helpers.entity_registry' (/usr/src/homeassistant/homeassistant/helpers/entity_registry.py)
> ```
> 
> It looks like this is related to the deprecation of `async_get_registry` as used in https://github.com/ianByrne/HASS-ukho_tides/blob/main/custom_components/ukho_tides/config_flow.py#L30 and https://github.com/ianByrne/HASS-ukho_tides/blob/main/custom_components/ukho_tides/config_flow.py#L215
> 
> I'm a Python idiot but it might be as simple as just replacing `async_get_registry` with `async_get` in those two lines?

**Comment by jfparis** [comment]
I did the same as @nharrison00 initially but it appears that everything is being renamed "async_get" in the helpers. I posted a PR with to follow the same conventions as in the core of home assistant and make the code slightly more readable 

PS: I love your work @ianByrne. Stumbled on in on Tuesday night after some failed scraping attempt

**Comment by ianByrne** [comment]
Fantastic, many thanks @jfparis ! That change is now merged in, so you should all be able to update through HACS and get it working again.
