### ISSUE TITLE
Document on how to sign up moved 

### ISSUE THREAD

**Issue by snigehere** [ianByrne/HASS-ukho_tides#23]
The URL for how to sign up to the API key in the read.me is no longer valid 

In this paragraph:

API Key
First up, you will need an API key from the Admiralty Maritime Data Solutions developer portal. Follow **their guide** on how to do so and select one of the UK Tidal API products - the Discovery tier is free (the paid APIs are untested for this integration, but should in theory work fine).

The URL I found this on was https://developer.admiralty.co.uk/docs/startup and here https://admiraltyapi.developer.azure-api.net/

**Comment by ianByrne** [comment]
Many thanks for the heads up - this has now been updated
