### ISSUE TITLE
Channel Islands

### ISSUE THREAD

**Issue by zarss** [ianByrne/HASS-ukho_tides#28]
Hi. If I may ask, could you please add Guernsey, Channel Islands to the list please? Thank you.

**Comment by ianByrne** [comment]
Hi @zarss - I think they should be coming up in the list under the following names:

- [ST. PETER PORT](https://easytide.admiralty.co.uk/?PortID=1604)
- [Maseline Pier](https://easytide.admiralty.co.uk/?PortID=1603A)

Please let me know if they aren't showing up under these names for you

**Comment by zarss** [comment]
I went trough the list three times, maybe I am blind, but didn't find neither of them.

**Comment by zarss** [comment]
They appeared in HA, but status "unavailable"

**Comment by ianByrne** [comment]
Dang. I will see if I can find some time tonight to dig into what's happening with those stations

**Comment by zarss** [comment]
Thank you very much!

**Comment by ianByrne** [comment]
Scratch that, re-reading the docs, it looks like the Channel Islands **_are_** only available to the paid tiers 😱 

[Discovery (free) tier](https://developer.admiralty.co.uk/product#product=uk-tidal-api):
>The ADMIRALTY UK Tidal API provides authoritative source of tidal height predictions for Standard and Secondary tidal level stations around the United Kingdom. Discovery provides a free 1-year subscription to access the current plus 6 days’ worth of tidal events for 607 tidal stations around the United Kingdom.
• 10 calls per second
• 10,000 calls per month

[Foundation (Paid) tier](https://developer.admiralty.co.uk/product#product=tidal-api-foundation):
> The Tidal API provides an authoritative source of tidal height predictions for Standard and Secondary tidal level stations.
Foundation provides a 1-year subscription to access the current plus 13 days’ worth of tidal height for a wide range of tidal height stations around the British Isles and Ireland. This includes The Isle of Man and The Channel Islands consisting of the Bailiwicks of Jersey and Guernsey.
• 20 calls per second
• 20,000 calls per month
1 year subscription - £120 ex VAT

I'm sorry that this appears to be the case. Do please let me know if you end up deciding to go with a paid subscription - I have not personally done this, so those endpoints are all untested for this integration, but they should in theory all still work fine.

**Comment by zarss** [comment]
Thank you for your research. Unfortunately, usual case - Channel Islands are part of the UK, but really nobody cares about them.
