### ISSUE TITLE
Stopped working November 2024

### ISSUE THREAD

**Issue by GeorgeBR** [ianByrne/HASS-ukho_tides#32]
I upgraded to version 71c9bed and everything stopped working. However, when I try to re-install I get an HTTP 500 error, so it appears the Admiralty service has stopped?

**Comment by GeorgeBR** [comment]
I used git to rollback to f500223 and it's working again. So it's definitely a bug in the later versions

**Comment by ianByrne** [comment]
Hi all - I'm sorry to hear that you're running into issues with the new version. Unfortunately, I haven't been able to replicate this error. I have a feeling that this newer version of the integration might require a newer version of Home Assistant too, as I've only been testing against the latest (`2024.11.3` as of writing). Can you please confirm if an update resolves the issue?

**Comment by fosterl2** [comment]
I'm on 2024.11.1, so will upgrade.
I was wondering if it has something to do with the base Python version that my Raspberry Pi is running, but will give 11.3 a whirl.

**Comment by ianByrne** [comment]
Hmm 2024.11.1 feels like it should be new enough already :/ Perhaps you're on to something with the underlying Raspberry Pi Python version. I may need to find lower versions of the dependent packages to make it more backward compatible but I'm afraid I am not sure when I will be able to get a chance to look into that

**Comment by fosterl2** [comment]
Brilliant! Yes, working fine on 2024.11.3.

Not sure if there is anyway you can include the HA version as a pre-req to upgrading

**Comment by ianByrne** [comment]
oh wow, that is a surprise :o but good to hear! Perhaps I can update the readme to mention the minimum HA version

**Comment by TomBrien** [comment]
So this is an error being thrown up by the package manager, uv, that Home Assistant uses. There is a conflict between the pinned version of aiohttp that HA states in its requirements (3.11.9 for HA 2024.12.1) and the upstream `ukhotides` package used here (which requires 3.10.11). This is probably made worse by HA 2024.12 transitioning to Python 3.13 which I think makes `aiohttp < 3.11` u usable. I think this can be addressed by changing the dependency in the upstream package to support `aiohttp = ">= 3.10.11"`.

**Comment by bouton** [comment]
I have just updated to HS 2024.12 and have same problem with it not loading.

`Logger: homeassistant.util.package
Source: util/package.py:152
First occurred: 11:17:41 PM (3 occurrences)
Last logged: 11:17:43 PM

Unable to install package ukhotides==1.1.1: × No solution found when resolving dependencies: ╰─▶ Because ukhotides==1.1.1 depends on aiohttp==3.10.11 and aiohttp==3.11.9, we can conclude that ukhotides==1.1.1 cannot be used. And because you require ukhotides==1.1.1, we can conclude that your requirements are unsatisfiable.`

**Comment by XoneDB4** [comment]
Updated HA Core to 2024.12.0 and the integration broke as described above. Rolled back to 2024.11.3 and now it's working again.

**Comment by ianByrne** [comment]
Hi all - there is a new version of ukho_tides (1.1.2) now available which should hopefully resolve this issue. Thanks to @TomBrien for implementing the fix

**Comment by bouton** [comment]
1.1.2 works fine on HA 2024.12.  Thanks you and TomBrien for the quick update.

**Comment by elyobelyob** [comment]
Now I'm posting a comment .. chill Winston .. it all gets fixed quickly ... 

Thanks to all the efforts, and not the mud slingers.

**Comment by elyobelyob** [comment]
Thanks for the swift update.
