### ISSUE TITLE
No longer working on 2024.12.0

### ISSUE THREAD

**Issue by apbarratt** [ianByrne/HASS-ukho_tides#34]
Not entirely sure I understand why, but this along with one other integration seems to be failing.

It would seem the folk over at Alexa Media Player ought to have known this was going to happen though given a ticket seemed to have predicted it during the beta stage.

I'm not sure this is related to the other issue mentioning the November release (which worked without issue for me) so figured I'd best create a new Issue.

The error I get says
```
Logger: homeassistant.setup
Source: setup.py:269
First occurred: 12:11:21 (2 occurrences)
Last logged: 12:11:26

Setup failed for custom integration 'alexa_media': Requirements for alexa_media not found: ['alexapy==1.29.4'].
Setup failed for custom integration 'ukho_tides': Requirements for ukho_tides not found: ['ukhotides==1.1.1'].
```

I'm afraid I'm not seeing any other logs but I'm guessing it's related to the upgrade of Python that this latest release brought in, thus needing new requirements in place.  Do let me know if I can enable any extra logging for you for more information.

I'm disabling both integrations for the time being.  My whole home assistant seems to be going very sluggish right now, I can't think how it could be these two integrations in particular causing that, especially given they're apparently failed so presumably can't be doing anything else right now.  I suspect this is the reason folk don't like downing point zero releases, but I've always been a risk taker that way I guess 😅

**Comment by ianByrne** [comment]
Hi @apbarratt thanks for logging this issue - it looks like the UKHO integration did indeed break with the Python package upgrades included in the new 2024.12 release. There is a new version of the integration now available (1.1.2) which should hopefully resolve it.

It looks like the alexa_media one is in a similar boat - I would suggest opening an issue on their github too to investigate.

Please let me know if you continue to see issues after the 1.1.2 upgrade
