### ISSUE TITLE
Issue following install of Home assistant 2024.12.0 - integration does not start

### ISSUE THREAD

**Issue by snigehere** [ianByrne/HASS-ukho_tides#35]
Looks to be a dependency issue which I have seen with a few integrations ... I don't know what incantation to add that will solve it.

2024-12-05 20:56:07.665 ERROR (SyncWorker_5) [homeassistant.util.package] Unable to install package ukhotides==1.1.1: × No solution found when resolving dependencies:
  ╰─▶ Because ukhotides==1.1.1 depends on aiohttp==3.10.11 and
      aiohttp==3.11.9, we can conclude that ukhotides==1.1.1 cannot be used.
      And because you require ukhotides==1.1.1, we can conclude that your
      requirements are unsatisfiable.

**Comment by snigehere** [comment]
closing - for some reason HACS did not alert me that there was an updated version of the integration (4a62c25) available.  Downloaded and now all working again

Thanks for the prompt resolution

**Comment by jouster1974** [comment]
also found that the update wasnt prompted but now all working fine
