### ISSUE TITLE
integration seems to have broken with upgrade to 2024.12

### ISSUE THREAD

**Issue by jouster1974** [ianByrne/HASS-ukho_tides#36]
this works fine on 2024.11.4 and all prior versions but on 2024.12 it fails to load

Logger: homeassistant.setup
Source: setup.py:269
First occurred: 18:25:00 (1 occurrences)
Last logged: 18:25:00

Setup failed for custom integration 'ukho_tides': Requirements for ukho_tides not found: ['ukhotides==1.1.1'].

winding back to 2024.11.3 instantly fixes things

**Comment by jouster1974** [comment]
still broken in 2024.12.1

**Comment by jouster1974** [comment]
#35

**Comment by jouster1974** [comment]
as per @snigehere this is fixed by manually updating in HACs

**Comment by ianByrne** [comment]
Many thanks for confirming
