### ISSUE TITLE
device_state_attributes error

### ISSUE THREAD

**Issue by bouton** [ianByrne/HASS-ukho_tides#5]
Logger: homeassistant.helpers.entity
Source: helpers/entity.py:549
...
Entity sensor.ventnor_tide (<class 'custom_components.ukho_tides.sensor.UkhoTidesSensor'>) implements device_state_attributes. Please report it to the custom component author.

I think it is on sensor.py line 158 device_state_attributes should now be extra_state_attributes?
Thanks

**Comment by ianByrne** [comment]
Thanks for bringing this to my attention - I can confirm I see the warning in my own logs too. I'll see if I can look into it tonight

**Comment by ianByrne** [comment]
Thanks again for the heads up - a new update should now be available via HACS (d48ec086f3deb1c5727ca9f8783d75d3a762cdc1)

**Comment by bouton** [comment]
wow - fast - thanks!
