### ISSUE TITLE
Idea/Request: AU market

### ISSUE THREAD

**Issue by weppa** [ianByrne/HASS-ukho_tides#9]
@ianByrne I really admire your work! Especially the ApexCharts integration. I was wondering if there's a possibility for you to create a similar project for the AU market, or if you could guide me towards resources to learn and potentially develop a similar project using Python. Thank you so much!

[Bureau of Meteorology - Gold Coast Seaway](http://www.bom.gov.au/australia/tides/#!/qld-gold-coast-seaway)

![image](https://user-images.githubusercontent.com/58678210/217077622-5a3a209b-c720-4961-8c82-8ca545fa9e4b.png)

**Comment by ianByrne** [comment]
Hi @weppa - many thanks for your comment.

I had a quick poke around the BOM website and it looks like it could be a bit tricky - at first glance I was unable to find a public facing API for tide prediction data, although I did note there is one for [general weather forecasts and observations](http://www.bom.gov.au/catalogue/data-feeds.shtml).

I did however find this [Home Assistant Community forum post](https://community.home-assistant.io/t/restful-sensor-json-help-australian-tide-predictions-bom/149663) which seems to refer to a way to programmatically get tide data, but I am not able to find any documentation, so exploring it would be a bit of work and we might still not be able to get all the data we might want (X days of predictions, etc).

With regards to writing your own integration - this project was my first attempt at doing so, and I mostly followed [this guide](https://developers.home-assistant.io/docs/creating_component_index/).

Hope that helps!

**Comment by weppa** [comment]
Thanks @ianByrne for your prompt response. I found an API over on [stormglass.io](https://stormglass.io/) that has AU data. However, I am still stumped what to do with it, I've attempted to use RESTful to no avail. All I want to achieve is what you did using ApexCharts, presumably using their [data_generator](https://github.com/RomRider/apexcharts-card#data_generator-option) option?
